Repository No-Country/c9-32-t-javareact, pull requests merged in 2023-02, with the labels that each got.

#1 Delete client directory
  client/.gitignore
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: good first issue

#2 [ADD] readme base
  README.md
Labels: documentation

#4 [fixing] new boilerplate draft
  client/.gitignore
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: good first issue

#5 [deploy] docker and github workflow
  .github/workflows/maven.yml
  .vscode/settings.json
  server/Dockerfile
  server/pom.xml
  server/src/main/resources/application-dev.properties
  server/src/main/resources/application-prod.properties
  server/src/main/resources/application-test.properties
  server/src/main/resources/application.properties
Labels: enhancement

#6 Fixing error in Railway with volume property inside Dockerfile
  server/Dockerfile
Labels: bug
